import type { ExerciseLibraryItem } from "./types";

export const exerciseLibrary: ExerciseLibraryItem[] = [
  {
    exercise: "Bench Press",
    muscleGroup: "Chest",
    equipment: "Barbell",
    target: "Mid chest, front delts, triceps",
    defaultSets: "3",
    defaultReps: "6-10",
    cues: ["Keep shoulder blades pinned", "Touch the same spot each rep", "Drive feet into the floor"],
    substitutions: ["Dumbbell Press", "Machine Chest Press", "Push-Up"],
  },
  {
    exercise: "Incline Dumbbell Press",
    muscleGroup: "Chest",
    equipment: "Dumbbells",
    target: "Upper chest",
    defaultSets: "3",
    defaultReps: "8-12",
    cues: ["Use a slight incline", "Lower under control", "Press up and slightly in"],
    substitutions: ["Incline Machine Press", "Incline Bench Press", "Cable Fly"],
  },
  {
    exercise: "Shoulder Press",
    muscleGroup: "Shoulders",
    equipment: "Barbell or dumbbells",
    target: "Front and side delts",
    defaultSets: "3",
    defaultReps: "6-10",
    cues: ["Brace before pressing", "Keep ribs down", "Finish with biceps near ears"],
    substitutions: ["Dumbbell Shoulder Press", "Machine Shoulder Press", "Arnold Press"],
  },
  {
    exercise: "Lat Pulldown",
    muscleGroup: "Back",
    equipment: "Cable machine",
    target: "Lats",
    defaultSets: "3",
    defaultReps: "8-12",
    cues: ["Pull elbows down", "Keep chest tall", "Control the stretch at the top"],
    substitutions: ["Pull-Up", "Assisted Pull-Up", "Single-Arm Pulldown"],
  },
  {
    exercise: "Barbell Row",
    muscleGroup: "Back",
    equipment: "Barbell",
    target: "Mid back and lats",
    defaultSets: "3",
    defaultReps: "6-10",
    cues: ["Hinge and brace", "Pull toward lower ribs", "Do not bounce the weight"],
    substitutions: ["Chest-Supported Row", "Seated Cable Row", "Dumbbell Row"],
  },
  {
    exercise: "Squat",
    muscleGroup: "Quads",
    equipment: "Barbell",
    target: "Quads, glutes, core",
    defaultSets: "3",
    defaultReps: "5-8",
    cues: ["Brace hard before descending", "Keep pressure through midfoot", "Drive up with chest and hips together"],
    substitutions: ["Leg Press", "Hack Squat", "Goblet Squat"],
  },
  {
    exercise: "Romanian Deadlift",
    muscleGroup: "Hamstrings",
    equipment: "Barbell or dumbbells",
    target: "Hamstrings and glutes",
    defaultSets: "3",
    defaultReps: "8-12",
    cues: ["Push hips back", "Keep shins mostly vertical", "Stop when hamstrings are fully stretched"],
    substitutions: ["Seated Leg Curl", "Lying Leg Curl", "Good Morning"],
  },
  {
    exercise: "Leg Press",
    muscleGroup: "Quads",
    equipment: "Machine",
    target: "Quads and glutes",
    defaultSets: "3",
    defaultReps: "10-15",
    cues: ["Use a deep controlled range", "Keep lower back on pad", "Do not lock knees hard"],
    substitutions: ["Hack Squat", "Squat", "Bulgarian Split Squat"],
  },
  {
    exercise: "Leg Curl",
    muscleGroup: "Hamstrings",
    equipment: "Machine",
    target: "Hamstrings",
    defaultSets: "3",
    defaultReps: "10-15",
    cues: ["Keep hips down", "Squeeze at the curl", "Control the negative"],
    substitutions: ["Romanian Deadlift", "Seated Leg Curl", "Lying Leg Curl"],
  },
  {
    exercise: "Tricep Pushdown",
    muscleGroup: "Triceps",
    equipment: "Cable machine",
    target: "Triceps",
    defaultSets: "3",
    defaultReps: "10-15",
    cues: ["Pin elbows near sides", "Fully extend each rep", "Control the return"],
    substitutions: ["Overhead Tricep Extension", "Skull Crusher", "Close-Grip Bench Press"],
  },
  {
    exercise: "Bicep Curl",
    muscleGroup: "Biceps",
    equipment: "Dumbbells, barbell, or cable",
    target: "Biceps",
    defaultSets: "3",
    defaultReps: "10-15",
    cues: ["Keep elbows steady", "Curl without swinging", "Squeeze at the top"],
    substitutions: ["Hammer Curl", "Cable Curl", "Preacher Curl"],
  },
  {
    exercise: "Calf Raise",
    muscleGroup: "Calves",
    equipment: "Machine or dumbbells",
    target: "Calves",
    defaultSets: "3",
    defaultReps: "12-20",
    cues: ["Pause at the stretched bottom", "Rise as high as possible", "Avoid bouncing"],
    substitutions: ["Seated Calf Raise", "Standing Calf Raise", "Leg Press Calf Raise"],
  },
  {
    exercise: "Lateral Raise",
    muscleGroup: "Shoulders",
    equipment: "Dumbbells or cable",
    target: "Side delts",
    defaultSets: "3",
    defaultReps: "12-20",
    cues: ["Lead with elbows", "Stop around shoulder height", "Keep tension controlled"],
    substitutions: ["Cable Lateral Raise", "Machine Lateral Raise", "Lean-Away Lateral Raise"],
  },
  {
    exercise: "Hip Thrust",
    muscleGroup: "Glutes",
    equipment: "Barbell or machine",
    target: "Glutes",
    defaultSets: "3",
    defaultReps: "8-12",
    cues: ["Tuck ribs down", "Pause at lockout", "Drive through heels"],
    substitutions: ["Glute Bridge", "Cable Pull-Through", "Romanian Deadlift"],
  },
  {
    exercise: "Plank",
    muscleGroup: "Core",
    equipment: "Bodyweight",
    target: "Core stability",
    defaultSets: "3",
    defaultReps: "30-60 sec",
    cues: ["Squeeze glutes", "Keep ribs down", "Hold a straight line"],
    substitutions: ["Dead Bug", "Pallof Press", "Hollow Hold"],
  },
  {
    exercise: "Push-Up",
    muscleGroup: "Chest",
    equipment: "Bodyweight",
    target: "Chest, front delts, triceps",
    defaultSets: "3",
    defaultReps: "8-20",
    cues: ["Keep a straight body line", "Lower chest between hands", "Press the floor away"],
    substitutions: ["Bench Press", "Machine Chest Press", "Dumbbell Press"],
  },
  {
    exercise: "Cable Fly",
    muscleGroup: "Chest",
    equipment: "Cable machine",
    target: "Chest isolation",
    defaultSets: "3",
    defaultReps: "10-15",
    cues: ["Keep elbows softly bent", "Bring hands together in front of chest", "Control the stretch"],
    substitutions: ["Pec Deck", "Dumbbell Fly", "Incline Cable Fly"],
  },
  {
    exercise: "Pec Deck",
    muscleGroup: "Chest",
    equipment: "Machine",
    target: "Chest isolation",
    defaultSets: "3",
    defaultReps: "10-15",
    cues: ["Keep chest tall", "Squeeze at the middle", "Return slowly"],
    substitutions: ["Cable Fly", "Dumbbell Fly", "Push-Up"],
  },
  {
    exercise: "Pull-Up",
    muscleGroup: "Back",
    equipment: "Bodyweight",
    target: "Lats and upper back",
    defaultSets: "3",
    defaultReps: "5-10",
    cues: ["Start from a full hang", "Drive elbows down", "Control the lower"],
    substitutions: ["Assisted Pull-Up", "Lat Pulldown", "Single-Arm Pulldown"],
  },
  {
    exercise: "Seated Cable Row",
    muscleGroup: "Back",
    equipment: "Cable machine",
    target: "Mid back and lats",
    defaultSets: "3",
    defaultReps: "8-12",
    cues: ["Sit tall", "Pull elbows behind body", "Do not lean back hard"],
    substitutions: ["Chest-Supported Row", "Barbell Row", "Dumbbell Row"],
  },
  {
    exercise: "Chest-Supported Row",
    muscleGroup: "Back",
    equipment: "Machine or dumbbells",
    target: "Mid back",
    defaultSets: "3",
    defaultReps: "8-12",
    cues: ["Keep chest on pad", "Pull through elbows", "Pause briefly at the top"],
    substitutions: ["Seated Cable Row", "Dumbbell Row", "Barbell Row"],
  },
  {
    exercise: "Face Pull",
    muscleGroup: "Shoulders",
    equipment: "Cable machine",
    target: "Rear delts and upper back",
    defaultSets: "3",
    defaultReps: "12-20",
    cues: ["Pull toward eye level", "Separate the rope", "Keep shoulders down"],
    substitutions: ["Reverse Pec Deck", "Rear Delt Fly", "Band Pull-Apart"],
  },
  {
    exercise: "Rear Delt Fly",
    muscleGroup: "Shoulders",
    equipment: "Dumbbells or machine",
    target: "Rear delts",
    defaultSets: "3",
    defaultReps: "12-20",
    cues: ["Lead with elbows", "Keep traps relaxed", "Use controlled reps"],
    substitutions: ["Reverse Pec Deck", "Face Pull", "Cable Rear Delt Fly"],
  },
  {
    exercise: "Arnold Press",
    muscleGroup: "Shoulders",
    equipment: "Dumbbells",
    target: "Front and side delts",
    defaultSets: "3",
    defaultReps: "8-12",
    cues: ["Rotate smoothly", "Keep ribs down", "Press without leaning back"],
    substitutions: ["Dumbbell Shoulder Press", "Machine Shoulder Press", "Shoulder Press"],
  },
  {
    exercise: "Preacher Curl",
    muscleGroup: "Biceps",
    equipment: "Bench, barbell, or machine",
    target: "Biceps",
    defaultSets: "3",
    defaultReps: "8-12",
    cues: ["Keep upper arms on pad", "Curl without bouncing", "Control the bottom"],
    substitutions: ["Cable Curl", "Bicep Curl", "Incline Dumbbell Curl"],
  },
  {
    exercise: "Hammer Curl",
    muscleGroup: "Biceps",
    equipment: "Dumbbells or rope cable",
    target: "Biceps and brachialis",
    defaultSets: "3",
    defaultReps: "10-15",
    cues: ["Keep thumbs up", "Avoid swinging", "Control each rep"],
    substitutions: ["Cable Curl", "Bicep Curl", "Reverse Curl"],
  },
  {
    exercise: "Incline Dumbbell Curl",
    muscleGroup: "Biceps",
    equipment: "Dumbbells",
    target: "Biceps in a stretched position",
    defaultSets: "3",
    defaultReps: "10-15",
    cues: ["Let arms hang behind torso", "Keep elbows quiet", "Squeeze at the top"],
    substitutions: ["Preacher Curl", "Cable Curl", "Bicep Curl"],
  },
  {
    exercise: "Skull Crusher",
    muscleGroup: "Triceps",
    equipment: "EZ bar or dumbbells",
    target: "Triceps",
    defaultSets: "3",
    defaultReps: "8-12",
    cues: ["Keep elbows pointed up", "Lower under control", "Extend without flaring"],
    substitutions: ["Overhead Tricep Extension", "Tricep Pushdown", "Close-Grip Bench Press"],
  },
  {
    exercise: "Overhead Tricep Extension",
    muscleGroup: "Triceps",
    equipment: "Cable or dumbbell",
    target: "Long head of triceps",
    defaultSets: "3",
    defaultReps: "10-15",
    cues: ["Keep elbows high", "Get a deep stretch", "Extend fully"],
    substitutions: ["Skull Crusher", "Tricep Pushdown", "Dips"],
  },
  {
    exercise: "Dips",
    muscleGroup: "Triceps",
    equipment: "Parallel bars or assisted machine",
    target: "Triceps, chest, front delts",
    defaultSets: "3",
    defaultReps: "6-12",
    cues: ["Keep shoulders controlled", "Lower to a comfortable depth", "Drive through the bars"],
    substitutions: ["Close-Grip Bench Press", "Push-Up", "Tricep Pushdown"],
  },
  {
    exercise: "Hack Squat",
    muscleGroup: "Quads",
    equipment: "Machine",
    target: "Quads and glutes",
    defaultSets: "3",
    defaultReps: "8-12",
    cues: ["Use a deep range", "Keep back on pad", "Drive through midfoot"],
    substitutions: ["Leg Press", "Squat", "Goblet Squat"],
  },
  {
    exercise: "Bulgarian Split Squat",
    muscleGroup: "Quads",
    equipment: "Dumbbells or bodyweight",
    target: "Quads and glutes",
    defaultSets: "3",
    defaultReps: "8-12",
    cues: ["Keep front foot planted", "Lower under control", "Drive through the front leg"],
    substitutions: ["Lunge", "Leg Press", "Goblet Squat"],
  },
  {
    exercise: "Walking Lunge",
    muscleGroup: "Quads",
    equipment: "Dumbbells or bodyweight",
    target: "Quads, glutes, balance",
    defaultSets: "3",
    defaultReps: "10-16",
    cues: ["Take controlled steps", "Keep torso tall", "Push through the front foot"],
    substitutions: ["Bulgarian Split Squat", "Reverse Lunge", "Leg Press"],
  },
  {
    exercise: "Leg Extension",
    muscleGroup: "Quads",
    equipment: "Machine",
    target: "Quads",
    defaultSets: "3",
    defaultReps: "10-15",
    cues: ["Set pad above ankles", "Squeeze at the top", "Lower slowly"],
    substitutions: ["Hack Squat", "Leg Press", "Sissy Squat"],
  },
  {
    exercise: "Seated Leg Curl",
    muscleGroup: "Hamstrings",
    equipment: "Machine",
    target: "Hamstrings",
    defaultSets: "3",
    defaultReps: "10-15",
    cues: ["Keep hips down", "Curl through a full range", "Control the return"],
    substitutions: ["Lying Leg Curl", "Romanian Deadlift", "Nordic Curl"],
  },
  {
    exercise: "Lying Leg Curl",
    muscleGroup: "Hamstrings",
    equipment: "Machine",
    target: "Hamstrings",
    defaultSets: "3",
    defaultReps: "10-15",
    cues: ["Keep hips pressed down", "Curl without jerking", "Pause when fully curled"],
    substitutions: ["Seated Leg Curl", "Romanian Deadlift", "Nordic Curl"],
  },
  {
    exercise: "Deadlift",
    muscleGroup: "Full Body",
    equipment: "Barbell",
    target: "Posterior chain, back, grip",
    defaultSets: "3",
    defaultReps: "3-6",
    cues: ["Brace before pulling", "Keep bar close", "Stand tall without overextending"],
    substitutions: ["Romanian Deadlift", "Trap Bar Deadlift", "Rack Pull"],
  },
  {
    exercise: "Glute Bridge",
    muscleGroup: "Glutes",
    equipment: "Barbell or bodyweight",
    target: "Glutes",
    defaultSets: "3",
    defaultReps: "10-15",
    cues: ["Tuck ribs down", "Drive through heels", "Pause at lockout"],
    substitutions: ["Hip Thrust", "Cable Pull-Through", "Romanian Deadlift"],
  },
  {
    exercise: "Cable Pull-Through",
    muscleGroup: "Glutes",
    equipment: "Cable machine",
    target: "Glutes and hamstrings",
    defaultSets: "3",
    defaultReps: "10-15",
    cues: ["Hinge at the hips", "Keep arms relaxed", "Squeeze glutes to stand"],
    substitutions: ["Hip Thrust", "Glute Bridge", "Romanian Deadlift"],
  },
  {
    exercise: "Seated Calf Raise",
    muscleGroup: "Calves",
    equipment: "Machine",
    target: "Soleus-focused calves",
    defaultSets: "3",
    defaultReps: "12-20",
    cues: ["Pause deep in the stretch", "Rise fully", "Avoid bouncing"],
    substitutions: ["Standing Calf Raise", "Leg Press Calf Raise", "Calf Raise"],
  },
  {
    exercise: "Standing Calf Raise",
    muscleGroup: "Calves",
    equipment: "Machine or dumbbells",
    target: "Gastrocnemius-focused calves",
    defaultSets: "3",
    defaultReps: "12-20",
    cues: ["Keep knees mostly straight", "Stretch at the bottom", "Pause at the top"],
    substitutions: ["Seated Calf Raise", "Leg Press Calf Raise", "Calf Raise"],
  },
  {
    exercise: "Hanging Leg Raise",
    muscleGroup: "Core",
    equipment: "Pull-up bar",
    target: "Abs and hip flexors",
    defaultSets: "3",
    defaultReps: "8-15",
    cues: ["Control the swing", "Curl pelvis upward", "Lower slowly"],
    substitutions: ["Captain's Chair Raise", "Reverse Crunch", "Dead Bug"],
  },
  {
    exercise: "Cable Crunch",
    muscleGroup: "Core",
    equipment: "Cable machine",
    target: "Abs",
    defaultSets: "3",
    defaultReps: "10-15",
    cues: ["Round through the spine", "Keep hips mostly still", "Squeeze abs hard"],
    substitutions: ["Machine Crunch", "Crunch", "Plank"],
  },
  {
    exercise: "Pallof Press",
    muscleGroup: "Core",
    equipment: "Cable or band",
    target: "Anti-rotation core strength",
    defaultSets: "3",
    defaultReps: "10-15",
    cues: ["Stand tall", "Press straight out", "Resist rotation"],
    substitutions: ["Side Plank", "Dead Bug", "Cable Chop"],
  },
  {
    exercise: "Wrist Curl",
    muscleGroup: "Forearms",
    equipment: "Dumbbells or barbell",
    target: "Forearm flexors",
    defaultSets: "3",
    defaultReps: "12-20",
    cues: ["Use a full wrist range", "Keep forearms supported", "Control the lowering"],
    substitutions: ["Reverse Curl", "Farmer Carry", "Cable Wrist Curl"],
  },
  {
    exercise: "Reverse Curl",
    muscleGroup: "Forearms",
    equipment: "EZ bar or dumbbells",
    target: "Forearms and brachialis",
    defaultSets: "3",
    defaultReps: "10-15",
    cues: ["Use an overhand grip", "Keep elbows still", "Avoid swinging"],
    substitutions: ["Hammer Curl", "Wrist Curl", "Cable Curl"],
  },
  {
    exercise: "Farmer Carry",
    muscleGroup: "Forearms",
    equipment: "Dumbbells or trap bar",
    target: "Grip, traps, core",
    defaultSets: "3",
    defaultReps: "30-60 sec",
    cues: ["Stand tall", "Walk under control", "Keep shoulders packed"],
    substitutions: ["Suitcase Carry", "Dead Hang", "Trap Bar Carry"],
  },
  {
    exercise: "Neck Flexion",
    muscleGroup: "Neck",
    equipment: "Harness, plate, or band",
    target: "Front neck",
    defaultSets: "2",
    defaultReps: "12-20",
    cues: ["Use light resistance", "Move slowly", "Stop if anything feels sharp"],
    substitutions: ["Isometric Neck Hold", "Neck Extension", "Manual Resistance Neck Flexion"],
  },
  {
    exercise: "Treadmill Run",
    muscleGroup: "Cardio",
    equipment: "Treadmill",
    target: "Cardiovascular conditioning",
    defaultSets: "1",
    defaultReps: "10-30 min",
    cues: ["Start easy", "Keep posture relaxed", "Progress time or pace slowly"],
    substitutions: ["Outdoor Run", "Bike", "Rowing Machine"],
  },
  {
    exercise: "Bike",
    muscleGroup: "Cardio",
    equipment: "Stationary bike",
    target: "Low-impact conditioning",
    defaultSets: "1",
    defaultReps: "10-30 min",
    cues: ["Set seat height comfortably", "Keep cadence smooth", "Progress resistance gradually"],
    substitutions: ["Treadmill Run", "Elliptical", "Rowing Machine"],
  },
  {
    exercise: "Rowing Machine",
    muscleGroup: "Cardio",
    equipment: "Rower",
    target: "Conditioning and posterior chain endurance",
    defaultSets: "1",
    defaultReps: "5-20 min",
    cues: ["Push with legs first", "Finish with arms", "Return under control"],
    substitutions: ["Bike", "Treadmill Run", "Ski Erg"],
  },
];
